### ISSUE TITLE
Product Data Tracking

### ISSUE THREAD

**Issue by BramWulteputte** [Blockstock-gg/blockstock-issues#4]
- [ ] Impressions
- [x] Clicks per product
- [ ] Click-through Rate
- [x] Conversion Rate
- [x] Favorites count (not public facing)
- [x] Saved Cart count
- [x] Search word database, with count
- [x] Amount of sales
